name= "pastebin-worker"
compatibility_date = "2023-11-28"
account_id= "6aaff1fa398a7a85ee79920a2ac8a6ef"
main = "src/index.ts"
workers_dev = false

vars = { ENVIRONMENT = "production" }
route = { pattern = "feige.setsailtowardstianhan.ip-ddns.com", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "fbb04bde38d543f8ae64bd0aba193a45" },
  { binding = "PBIMGS", id ="bab43e290224466b996f5fee65c246df" }
]

[site]
bucket = "./static/dist"
